name: GCC

on: push

jobs:
  gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 9
            os: ubuntu-22.04
          - version: 10
            os: ubuntu-24.04
          - version: 11
            os: ubuntu-24.04
          - version: 12
            os: ubuntu-24.04
          - version: 13
            os: ubuntu-24.04
          - version: 14
            os: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-${{ matrix.version }} libglfw3-dev libgl-dev pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../
          make -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
